---
- name: debian | install memcache module for php
  apt: name={{apt_package}} state=installed

- name: debian | enable memcache module for php
  command: php5enmod {{php_memcache_ini_filename}}
  args:
    creates: "{{ansible_local.phpinfo_core.php_config_file_scan_dir}}/{{php_memcache_extension_priority}}-{{php_memcache_ini_filename}}.ini"
